# Project: Project9
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "file\ copy.o" Untitled2.o "file\ copy\ program.o" "file\ copy\ txt1.o"
LINKOBJ  = "file copy.o" Untitled2.o "file copy program.o" "file copy txt1.o"
LIBS     = -L"C:/Users/Dell/Desktop/C/Dev-Cpp/MinGW64/lib" -L"C:/Users/Dell/Desktop/C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows
INCS     = -I"C:/Users/Dell/Desktop/C/Dev-Cpp/MinGW64/include" -I"C:/Users/Dell/Desktop/C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Dell/Desktop/C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Dell/Desktop/C/Dev-Cpp/MinGW64/include" -I"C:/Users/Dell/Desktop/C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Dell/Desktop/C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Dell/Desktop/C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = file3.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"file\ copy.o": file\ copy.cpp
	$(CPP) -c "file copy.cpp" -o "file copy.o" $(CXXFLAGS)

"file\ copy\ program.o": file\ copy\ program.cpp
	$(CPP) -c "file copy program.cpp" -o "file copy program.o" $(CXXFLAGS)

"file\ copy\ txt1.o": file\ copy\ txt1.cpp
	$(CPP) -c "file copy txt1.cpp" -o "file copy txt1.o" $(CXXFLAGS)
